### ISSUE TITLE
Where Are Save Files Stored On Desktop?

### ISSUE THREAD

**Issue by AFM-Horizon** [encryptic-team/encryptic#105]
Just wondering where the files are stored on the windows desktop version, all my notes seem to have disappeared and I was hoping to manually search for them!

**Comment by daed** [comment]
The files should be located in the application data for electron.  I think that's Users\<username>\AppData\Local\encryptic.  See https://github.com/electron/electron/issues/10831

I've never tried to recover them via files like that, so I hope that it works for you.  If you find them and they're encrypted, I have a script that can decrypt them so long as you have access to your private key.  It's not in git, so let me know if you can get that far.

I've had a few reports of missing notes and that's a little worrying, but I haven't been able to reproduce it, unfortunately.

**Comment by daed** [comment]
Closing this as it hasn't been updated for some time.

@AFM-Horizon if this is something you're interested in still and want more help, feel free to reopen/let me know.
