### ISSUE TITLE
Deletion of a notebook

### ISSUE THREAD

**Issue by nazmifr** [encryptic-team/encryptic#16]
Hi,
(previously posted on the Laverna repository)
I've been using Laverna for a few hours, seems to be right for my needs (note taking in school+project management+reading notes), I have created a few redundant notebooks and can't seem to find a way to delete them, am I blind or is there no option to do so.

If there isn't, I guess that would be a great suggestion of a feature for a next version.

PS: I'm using the version provided by yunohost (Beta v0.7.51)

**Comment by daed** [comment]
Laverna 0.7.51 is not supported by anyone currently.  Our codebase is based on the dev branch of Laverna which actually has very little in common with the one in 0.7.51.  

I took a look at it though and if you go to Notebooks & Tags, each notebook should have a button to the right of it with a little down arrow on it.  If it's not there you might need to go back to the note view and then look again.  Seems like it isn't drawn if a new notebook gets added in the same view.  There should be a "Remove" option when you click that.  

Hope that helps!

**Comment by nazmifr** [comment]
Hi,
I'm sorry I didn't see the notification from github, thank you a lot for your message, I'm switching to the new encryptic then. :) 

Thank your for the searching of where the delete button is. That's really helpful as I didn't need some notebooks anymore and they were taking room in the interface.

Thank you for your work keeping the project alive
