### ISSUE TITLE
Dropbox folder name is LavernaNG

### ISSUE THREAD

**Issue by ghosttie** [encryptic-team/encryptic#20]
When you set it up to sync using Dropbox it creates a folder in the Apps folder called LavernaNG not encryptic

**Comment by daed** [comment]
That's a holdover from before the project was rebranded.  I'll clean it up in the future as I need to entirely revamp the dropbox module, but it has to stay where it is now because I don't want to break any early adopters until I have a migration mechanism in place.

**Comment by daed** [comment]
I changed this so it should be using the folder at apps/Encryptic.
