### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by ghosttie** [encryptic-team/encryptic#21]
It would be nice if buttons that only have images on them had tooltips to help users discover what the button does

**Comment by daed** [comment]
This was a pretty quick one so I got them added tonight.  They are committed to master and also pushed to app.encryptic.org.

![tooltip](https://user-images.githubusercontent.com/1466660/48247358-a23a0880-e3b8-11e8-83e3-564889dd6393.png)

You might need to refresh to make sure that your browser isn't caching the css.
