### ISSUE TITLE
Ticking ToDo's in Preview

### ISSUE THREAD

**Issue by SeaLife** [encryptic-team/encryptic#32]
Heyho,

would like to use this as my ToDo list for my work....

But i would like to tick these Checkboxes in Edit mode to finish my tasks... (switching between saved mode and edit mode is not practical for me)...

Its working in Boostnote (i was using it before this one) but you cant host Boostnote as a web application..

Is it possible to update the Markdown to these `- [x]` and to `- [ ]` if you check/uncheck the corresponding item in the preview (its working in the saved mode ;)).

Regards
SeaLife

**Comment by Maks-s** [comment]
I'm working on it 👨‍🏭

**Comment by daed** [comment]
@SeaLife this change has been merged.  It'll be included in the next release, which is hopefully not too far off now.
