### ISSUE TITLE
Better logging when electron/self-hosted doesn't start up correctly.

### ISSUE THREAD

**Issue by daed** [encryptic-team/encryptic#37]
See https://github.com/Laverna/laverna/issues/985 for background.

Docker competes for port 9000.  Maybe we can display something informative if the webserver can't start because port is in use?

**Comment by Maks-s** [comment]
Or we can change the port, and if it's also used then check the next one.
As we don't want to check 56535 port, we can just check for number 9000 to 9000 + X

**Comment by daed** [comment]
That would work for desktop versions.  If you run it as a server, I would think that you'd wouldn't want inconsistency there.

**Comment by pms1969** [comment]
VSCode does this very well if you're looking for an example.

**Comment by daed** [comment]
@Maks-s put in a check and error message for this via #74.  I don't know if we should talk about changing ports to something less commonly used or if this is enough, but I think I'm satisfied with, at least for the time being.
