### ISSUE TITLE
Misaligned Menu Title 

### ISSUE THREAD

**Issue by pranavgaikwad** [encryptic-team/encryptic#49]
I use Google Chrome Version 71.0.3578.98 on a Linux Mint 18.3 machine.

Screen Size : 1366x768

When I open 'Notebooks & Tags' section from hamburger menu button, the _'New Note'_ button falls down on a new line disturbing whole alignment. It also overlaps the _'New Tag'_ button. See screenshot

![notebooks_alignment](https://user-images.githubusercontent.com/9839757/50377581-d3c80580-05ed-11e9-9404-25c0ad136c7f.png)

**Comment by Maks-s** [comment]
More infos: This bug happens when the width of the window is between 1200 and 1463px inclusive or between 768 and 894px inclusive

**Comment by Prune2000** [comment]
I'll have a look at it tonight. Probably some work to do on the responsive part of the web app.
