### ISSUE TITLE
Dark theme blinking

### ISSUE THREAD

**Issue by Prune2000** [encryptic-team/encryptic#70]
This is a continuation of the issue #15 but focused on the web app.

I have noticed that the dark theme is constantly blinking every time the user switches pages or create new notes, tags and notebooks. It seems that it's due to the code loading the default theme first, and then applying the settings that the user chose, so in this case the dark theme. It creates a half a second white blink before the dark theme.

I'll investigate and try to propose a solution soon.

**Comment by Prune2000** [comment]
Ok, I see now.

`<link rel="stylesheet" href="styles/theme-default.css" id="lav--theme">` 
is directly placed in the HTML so it loads this one first before any script takes action.

Then in utils/themes.js, it will fetch the settings (in our case dark theme) and apply it with 
`$('#lav--theme').attr('href', `styles/theme-${theme || 'default'}.css`);`

Gotta run for now but there must be an easier way to manage the themes to avoid this I imagine.

**Comment by Prune2000** [comment]
The fix by Maks-s seem to have solved it for me. Anyone else still experiencing the bug? Otherwise we can close.

**Comment by daed** [comment]
Closing for now.  Will reopen if anyone notices an issue.
