### ISSUE TITLE
Multiple "mode" issues with web app

### ISSUE THREAD

**Issue by rcrx** [encryptic-team/encryptic#83]
Having just tried the web app I find it quite unusable.

How, exactly, are you supposed to use a "Vim mode" that tries to close the document (complete with prompt) every time you hit the escape key?

The other issue is with the mode button on the task bar, which was totally unresponsive despite testing with multiple browsers and extensions disabled.

**Comment by Maks-s** [comment]
hi @rcrx 😺 

The "Vim mode" is misleading. In fact, it only changes the keybindings

Sorry about that, the issue with the mode button was fixed 22 days ago but app.encryptic.org isn't up-to-date

**Comment by daed** [comment]
I've been keeping app.encryptic.org only up to date with the most current release so we don't end up with weird version issues.  I will cut a release (for this and especially the import fixes) tonight and update the site as well.  

Would it be worth something to have a "unstable.encryptic.org" or something like that which would contain the latest master commit?  I could probably script it so that it wouldn't be too much overhead.

**Comment by Maks-s** [comment]
I think having an "unstable channel" for the web app would be nice, or maybe more frequent releases ?

**Comment by daed** [comment]
So app.encryptic.org is now updated @ 0.0.4.  Releases to follow shortly.

This should include the mode button change.

**Comment by daed** [comment]
Releases are up and so is https://unstable.encryptic.org.  It still requires manual intervention to push updates to, but I will eventually have it set up to something closer to a weekly or even nightly.

**Comment by daed** [comment]
So, there's no actual issue here (as of now) other than that the "vim mode" description is ambiguous, right?    Any thoughts on what we should change that to?  Maybe call it "hjkl navigation"?

**Comment by Maks-s** [comment]
After some digging, I found out "Vim mode" is really vim (https://codemirror.net/demo/vim.html), same for Emacs and Sublime, sorry for my mistake.

Yup, Vim mode is quite unusable with the escape key closing the note, also the prompt is semi-hidden (see screenshot).

![2019-04-03_13-28-40](https://user-images.githubusercontent.com/26678512/55475514-6d06af00-5614-11e9-952a-c21880dbd502.png)

We will try to fix this. Thanks for reporting the issue and really sorry for my mistake 😸

**Comment by daed** [comment]
Damn.  Good catch @Maks-s.  I should have taken a closer look.

So I know how to fix the Escape issue.  I can have that pushed today after work.  

However, using Firefox on Arch, I don't seem to have a cursor, and I can't see the prompt bar at all.  I tried with dark and light themes.  

With Chromium I can see the prompt bar cut off like in your screenshot (note: if line numbers are enabled, they'll also cover the prompt).  

With Chromium on dark mode, the prompt bar has white text on white background, making it impossible to read.  There is also no cursor.  Highlighting the text shows a blinking cursor in the highlighted area, so maybe it's a question of CSS?

**Comment by rcrx** [comment]
> However, using Firefox on Arch, I don't seem to have a cursor, and I can't see the prompt bar at all. I tried with dark and light themes.

That was the case for me as well.
 
 > So, there's no actual issue here (as of now) other than that the "vim mode" description is ambiguous, right? Any thoughts on what we should change that to? Maybe call it "hjkl navigation"?

If you're still interested in changing the name, I believe the Vim-like mode extension for Sublime is called "Vintage mode."

**Comment by daed** [comment]
Noted on the name change.  Once we get it working the way it's supposed to, I guess I'll see how vim-like it is and if it seems misleading still, maybe we can change it then.  

I pushed the escape fix to master.  Not going to be able to get to the other issues tonight, but I'm hoping they'll just be some simple css tweaks.

**Comment by rcrx** [comment]
Might have come up with something that could help, if you can incorporate it into the editor. I found a browser extension that, once installed, (seemingly) fixes *all* the Vim-related issues. It even takes care of the escape problem and allows for custom keymaps. It's called [wasavi](https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe?pli=1) and the source code is located [here](https://github.com/akahuku/wasavi). If nothing else, perhaps until the Vim mode is fixed you just say "install Wasavi for Vi mode" or some such. At least for the time being it serves as a fix for me (though it's Vi not Vim). I tried out some comparable extensions & they were either absurdly complicated to install, didn't work with Encryptic (among other online editors), simply didn't function at all, or didn't have the source code available... so Wasavi seemed the best option.

Hope this is useful, guys.
