### ISSUE TITLE
DropBox sync setup fail

### ISSUE THREAD

**Issue by dayfuaim** [encryptic-team/encryptic#93]
I use https://app.encryptic.org.
When trying to set up DropBox sync, I have successfully got the key from DropBox.
But nothing changed (even after refresh) in Encryptic.
I got the following in console:
![Снимок экрана 2019-05-15 в 14 49 21](https://user-images.githubusercontent.com/1274699/57773567-f84d8700-7720-11e9-885d-a28f1d835ee5.png)

When in https://unstable.encryptic.org, I get just that from DropBox (if I try to get the key, https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=XXXXXXXXXX&redirect_uri=https://unstable.encryptic.org/auth.html):
![Снимок экрана 2019-05-15 в 15 01 31](https://user-images.githubusercontent.com/1274699/57774120-5c247f80-7722-11e9-8fa9-bf4e332a55d8.png)
...and the same `"Global fetch is deprecated..."` error in console.
https://unstable.encryptic.org/auth.html is accessible.

**Comment by daed** [comment]
I have fixed this.  Just tried it and it works now.

Sorry about that.

**Comment by dayfuaim** [comment]
Thank you @daed.
Now sync setup really works. 😄
