### ISSUE TITLE
Dropbox SYNC fail

### ISSUE THREAD

**Issue by dayfuaim** [encryptic-team/encryptic#95]
Yes, Dropbox Sync setup is now working. Thank you @daed, you are great 👍 

I use https://unstable.encryptic.com and try to sync at last.
But now I get such a picture:
![Снимок экрана 2019-06-06 в 11 01 31](https://user-images.githubusercontent.com/1274699/59016771-b0ff7580-884a-11e9-9e81-91dc1bd3eddb.png)

The whole sync stops at `Validation error: title` line, although some of models dumped have title (I opened one as it can be seen), some not.

It's next bug.

**Comment by daed** [comment]
I have a theory that this is related to the restore/import bug in #90.

**Comment by dayfuaim** [comment]
@daed Please see https://github.com/encryptic-team/encryptic/issues/90#issuecomment-502047678

**Comment by dayfuaim** [comment]
@dead Dropbox sync works now.
But while having many "Error 429"'s, you will have to do sync (tap "Sync" button) several times – depends upon size of your notes library.
With each next sync amount of 429's lessens (~2x each time) and one sweet moment sync goes smooth. :)

So I think to close _this current_ bug.

**Comment by daed** [comment]
Yeah, I'm going to close this and reopen.  I know Dropbox's api only allows so many requests at a time.  Maybe I can have it automatically restart the sync if it detects errors?  I'll see what I can do to improve this.
