### ISSUE TITLE
KaTEX render bug

### ISSUE THREAD

**Issue by dayfuaim** [encryptic-team/encryptic#98]
After yesterday (26.06.) update at https://unstable.encryptic.org, KaTEX rendering is not correct:
![Снимок экрана 2019-06-27 в 13 54 44](https://user-images.githubusercontent.com/1274699/60260992-8782b880-98e3-11e9-8b97-5d1451026f81.png)

Reference (locally built copy from current master with same updates):
![Снимок экрана 2019-06-27 в 13 54 16](https://user-images.githubusercontent.com/1274699/60261047-9f5a3c80-98e3-11e9-9f42-d53cb8564720.png)

The code is: 
[MathJax samples.md.zip](https://github.com/encryptic-team/encryptic/files/3334281/MathJax.samples.md.zip)

Looks like Katex fonts loaded wrong (or corrupted).

**Comment by daed** [comment]
I could replicate.  I did the push out to unstable again.  Didn't change anything but that.  It looks like it's working right again for me.  Maybe a font got hosed during the initial push?  Not sure.

**Comment by dayfuaim** [comment]
@daed I have verified it now at https://unstable.encryptic.org/ – it works. :)
So I am going to close this issue.
